# List of folders where posts are stored
# Content from multiple sources must be unique!
sources:
- ~/Documents/exampledata/content1
- ~/Documents/exampledata/content2

# Folder where pages are stored
# Must not be in a subfolder where posts are stored
pages_folder: ~/Documents/exampledata/pages/

# Order in which pages are to appear in menu
pages_order:
  - index.md
  - anotherthing.md
  - about.md

# Where to store generated output
output: ~/Documents/artblog_output

# Include image at the top of every page above the menu
# Example designed using https://flamingtext.com/ for non-commercial use
# About 300 pixels wide, and less than 80 pixels in height works well
logo: ~/Documents/exampledata/logo/example_art_blog.png

# Include image for favicon (image in browser tabs)
# Example designed using https://favicon.io/favicon-generator/
# 32x32 pixels seems suitable
favicon: ~/Documents/exampledata/favicon/favicon-32x32.png

# Information about yourself and the site
author: Artsy Fartsy

# This doesn't have to be different from your name
site_name: My Awesome Art Blog

# Note: update license.html using https://creativecommons.org/choose/
#       for something different from CC by 4.0

# Leave this commented to automatically set to the current year
# copyright_year: 2021

# Important - Once you set this, don't change it (for SEO reasons)
# You will need to copy the output to the appropriate folder at your hosting site
base_url: https://myartblog.com
