# List of folders where articles are stored
sources:
- ~/Documents/artblog-example-data1/content
- ~/Documents/artblog-example-data2/content

# List of page files
page_sources: 
  - ~/Documents/artblog-example-data1/pages/index.md
  - ~/Documents/artblog-example-data1/pages/anotherthing.md
  - ~/Documents/artblog-example-data1/pages/about.md

# Where to store generated output
output: ~/Documents/artblog_output

# Information about yourself and the site
author: Firstname Lastname

# This doesn't have to be different from your name
site_name: My Awesome Art Blog

# Include image at the top of every page above the menu
# Example designed using https://flamingtext.com/ for non-commercial use
# About 300 pixels wide, and less than 80 pixels in height works well
logo: ~/Documents/artblog-example-data1/logo/example_art_blog.png

# Include image for favicon (image in browser tabs)
# Example designed using https://favicon.io/favicon-generator/
# 32x32 pixels seems suitable
favicon: ~/Documents/artblog-example-data1/favicon/favicon-32x32.png

# Note: update license.html using https://creativecommons.org/choose/
#       for something different from CC by 4.0

# Leave this commented to automatically set to the current year
# copyright_year: 2021

# Important - Once you set this, don't change it (for SEO reasons)
# You will need to copy the output to the appropriate folder at your hosting site
base_url: https://myartblog.com

# Files linked to navigation bar, from left to right
pages:
  - index.md
  - about.md
